# Generated by Django 6.0.5 on 2026-05-24 13:49

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='CanvasSession',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('session_key', models.CharField(db_index=True, max_length=40)),
                ('session_id', models.UUIDField(default=uuid.uuid4, editable=False, unique=True)),
                ('patient', models.JSONField(default=dict)),
                ('drugs', models.JSONField(default=list)),
                ('contraindications', models.JSONField(default=list)),
                ('decisions', models.JSONField(default=list)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ['-updated_at'],
            },
        ),
    ]
