# Generated by Django 6.0.5 on 2026-05-24 13:49

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='EvidanceSettings',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('session_key', models.CharField(db_index=True, max_length=40, unique=True)),
                ('active_sources', models.JSONField(default=list)),
                ('disease_focus', models.JSONField(default=list)),
                ('region', models.CharField(default='west_africa', max_length=20)),
                ('export_format', models.CharField(default='pdf', max_length=10)),
                ('canvas_persist', models.BooleanField(default=True)),
                ('theme', models.CharField(default='dark', max_length=10)),
                ('show_confidence', models.BooleanField(default=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'EvidAnce Settings',
                'verbose_name_plural': 'EvidAnce Settings',
            },
        ),
    ]
